FROM apache/airflow:latest

USER root

COPY . .

VOLUME [ "/airflow/dags", "/airflow/logs"]

RUN apt-get update
RUN apt-get install -y vim htop

ENTRYPOINT ["/usr/bin/dumb-init", "--"]
CMD ["airflow", "standalone"]
