FROM apache/airflow:slim-3.1.3-python3.12


USER root


RUN apt-get update \
 && apt-get install -y --no-install-recommends vim htop \
 && rm -rf /var/lib/apt/lists/*


USER airflow


WORKDIR /opt/airflow


COPY --chown=airflow:airflow dags/ ${AIRFLOW_HOME}/dags/
COPY --chown=airflow:airflow plugins/ ${AIRFLOW_HOME}/plugins/


CMD ["airflow", "standalone"]